language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk7
  - openjdk7
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "aurelien-baudet-github"
branches:
  except:
    - test/.*
    - gh-.*
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.integration.tests=true -Dskip.unit.tests=true -B -q
script: mvn test verify sonar:sonar javadoc:javadoc -Dmaven.test.redirectTestOutputToFile=true -B -q