language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
branches:
  except:
    - test/.*
    - gh-.*
script: mvn clean install verify -B -q