language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk7
  - openjdk7
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
branches:
  except:
    - test/.*
    - gh-.*
  sonarqube:
    organization: "aurelien-baudet-github"
script: mvn clean install verify sonar:sonar -B -q